services:
  db:
    image: postgres:15.1-alpine
    environment:
     POSTGRES_PASSWORD: 123Sest
     POSTGRES_DB: Dest
     POSTGRES_USER: test
    networks:
      - todo
    ports: 
     - "5432:5432"
    volumes: 
      - todo:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready", "-U", "test","-d","Dest"]
      interval: 10s
      timeout: 5s
      retries: 5
  fastapi:
    build: .
    depends_on:
       db:
         condition: service_healthy
    networks:
      - todo
    ports: 
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://test:123Sest@db:5432/Dest"
      SECRET_KEY: "7ca5b72db3d6ed19b2e34ff21739730839510daf95eb4ce6bd14931d50bc4123"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  todo:

networks:
  todo:
    driver: bridge
    