name: Docker Publish
on:
  push:         #once a new released started , pushing image will be 
          
permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{github.repository_owner}}/todo:latest
            ghcr.io/${{github.repository_owner}}/todo:${{github.event.release.tag_name}}